### ISSUE TITLE
Unclear how to "just open a terminal"

### ISSUE THREAD

**Issue by cideM** [rebelot/terminal.nvim#3]
Whatever I do, I am always prompted for a command. The result is that once the command is done, the shell exits. Am I maybe misunderstanding something about this plugin? I thought `:TermOpen botright 16 new` would just open a new terminal, where I can then run whatever shell commands I want. Basically, I thought it was some sort of wrapper around `:terminal` with some convenience functionality.

**Comment by rebelot** [comment]
just press `<Enter>` to skip the prompt and execute the interactive shell

**Comment by cideM** [comment]
But the pressing `<Enter>` part is pretty annoying. I interpret this as: what you want to do is not what this plugin was meant to solve?

**Comment by rebelot** [comment]
I don't think there's much doubt on what this plugin does. TermOpen is meant to open already existent terminals, if there's none, it will execute TermRun, which by default prompts the user for a command if it is not supplied, but the prompt can be skipped by pressing enter. there's a couple of solutions:

1. `:bot 16 new | TermRun! zsh`
2. `:exe "TermRun zsh" | TermMove bot 16 new`

I am open for suggestions on how to provide a better UI

**Comment by rebelot** [comment]
Btw, this plugin automatically captures all opened terminal, so you could just use `bot 16 new | term` and all actions provided by this plugin will affect the spawned terminal

**Comment by cideM** [comment]
Thank you for these explanations, this was very helpful 👍🏻 . Indeed, there's no need to open a terminal through the API.
